DROP TABLE IF EXISTS "stockbuild";
CREATE TABLE "stockbuild" (
	"Symbol" VARCHAR NULL DEFAULT NULL,
	"Date" DATE NULL DEFAULT NULL,
	"Open" DOUBLE PRECISION NULL DEFAULT NULL,
	"High" DOUBLE PRECISION NULL DEFAULT NULL,
	"Low" DOUBLE PRECISION NULL DEFAULT NULL,
	"Close" DOUBLE PRECISION NULL DEFAULT NULL,
	"StockBuildID" SERIAL NOT NULL,
	PRIMARY KEY ("StockBuildID")
)
